### ISSUE TITLE
if helm-certgen binary is not present, the wrapper script should should present better error message

### ISSUE THREAD

**Issue by saurabhsurana** [SUSE/helm-certgen#11]
Currently if helm-certgen binary is not present the error seen by the user is something like this
```
helm-certgen (master) # helm certgen generate sample/go-demo-app --namespace sample-go-demo-app
/Users/saurabh/.helm/plugins/certgen/certgen.sh: line 47: type: helm-certgen: not found
helm-certgen client needs to be installed
Error: plugin "certgen" exited with error
```

The check we are doing with `type` on line 47 in wrapper script needs to be better or at least should not print line on the console.

**Comment by saurabhsurana-zz** [comment]
This issue is addressed in [cf3450c0d5f450042ef3ad810d247c853260ea0a](https://github.com/SUSE/helm-certgen/commit/cf3450c0d5f450042ef3ad810d247c853260ea0a)
