### ISSUE TITLE
Provide a full release than can be installed with `helm plugin install`

### ISSUE THREAD

**Issue by jandubois** [SUSE/helm-certgen#16]
The current requirement of building the plugin locally and manually copying scripts around are impractical for end-users who just want to deploy a chart that uses this plugin.

**Comment by saurabhsurana-zz** [comment]
We have now changed the way we package and ship the plugin. With the first release 1.0.0 of the plugin, the binaries for Linux and Mac can be downloaded from release page and can be installed using the helm plugin install command directly.

There is also an option of being able to build the plugin locally if required.

@jandubois let me know if you have further concerns regarding this, otherwise, I would like to close this issue.

**Comment by jandubois** [comment]
@saurabhsurana This is obviously a lot better already, but I would really like to see

```
helm plugin install https://github.com/SUSE/helm-certgen
```

do the right thing. I guess this would mean checking the binaries into git, which is a bit distasteful, but maybe the plugin could be in a separate repo, with the source code repo as a submodule or something.

One advantage of this approach is that you have an easily scriptable mechanism to install the latest version of the plugin everywhere.

**Comment by saurabhsurana-zz** [comment]
@jandubois We discussed this approach but don't see any use of putting binaries in the git repo. The way install command works it needs the base path of the repo something that it can clone and it puts everything from the repo inside the plugin directory. So if we do this we will have to create a separate repo which only holds the binary. 

Instead, it will be better to support HTTP URL on helm plugin install command (and not just a github repository), such that you can directly specify the URL on the command and won't have to download the plugin separately.  Something like 
```
helm plugin install http://download.opensuse.org/repositories/home:/saurabhsuranasuse:/helm-certgen/openSUSE_Leap_42.2/certgen-linux-amd64-1-0-0-1501794790-f3b21c90.tgz
```

This needs changes on the CLI and it will take a bit of time, so until then we will have to live with the manual step of downloading the extracting the package locally.

**Comment by jandubois** [comment]
Ok, that is fine too, as long as you have a predictable URL and the user doesn't have to manually look it up on a releases list. So just have a `latest` alias to the URL that embeds the full version number.
